important: check file before install it.

diff --git a/gpkg/gpkg b/gpkg/gpkg
--- a/gpkg/gpkg
+++ b/gpkg/gpkg
@@ -56,7 +56,7 @@ BRACKET="\\033[1;34m" # Brackets are blue
 #
 # version and  usage 
 #
-gpkg_version=0.10.24
+gpkg_version=0.10.25
 gpkg_usage="
 gpkg $SUCCESS$gpkg_version$NORMAL, usage:\n
 	$INFO\t-v            	$NORMAL\t\tshow current version\n
@@ -941,16 +941,7 @@ gpkg_begininstall()
 
 	if [ "$pack_only" == "0" ]; then
 		#copy to root
-		showinfo ">> Moving files to $XGROOT/ ..."
-		tar xjpf $XGPATH_PACKAGE/$N-$V$R.xgp -C $XGROOT/
-		err_check "[Error] copy binary package to $XGROOT/ failed"
-		showinfo ">> Install OK, cleaning up.."
-	
-		#post install
-		xgb_postinst
-		err_check "[Error] call xgb_postinst failed"
-
-		showOK "[***] $N-$V$R installed to your system."
+		gpkg_install_binary_package $XGPATH_PACKAGE/$N-$V$R.xgp
 	else
 		showinfo ">> $XGPATH_PACKAGE/$N-$V$R.xgp is ready."
 	fi
@@ -1164,12 +1155,18 @@ gpkg_csvop_ls()
 		printf "$NORMAL%s| %8s| $FAILURE%s\n" " " "${value[2]}" "${value[1]}"
 		;;
 
-	*)
+	I)
 		#totle
 		printf "$WARNING\nFile: %s, Dir: %s, Link %d, Size: %dK\n" \
 			"${value[1]}"\
 			"${value[2]}" "${value[3]}" "${value[5]}"
 		;;
+
+	*)
+		#unknown
+		printf "$NORMAL%s| %8s| $FAILURE%s\n" " " "${value[2]}" "${value[1]}"
+		;;
+
 	esac
 	
 }
@@ -1187,11 +1184,57 @@ gpkg_csvop_rm_file()
 		unlink "$XGROOT${value[1]}"
 		printf "Remove file %s\n" "${value[1]}"
 		;;
+	O)
+		#device or other
+		unlink "$XGROOT${value[1]}"
+		printf "Remove file %s\n" "${value[1]}"
+		;;
+
 	esac
 	
 }
 
+gpkg_csvop_check_file()
+{
+	local cname
 
+	cname="$XGROOT${value[1]}"
+
+	case "${value[0]}" in
+	S)
+		#symbol.
+		echo  "OK   (S) $XGROOT${value[1]}"
+		;;
+	F)
+		#file
+		if [ -f "$cname" ]; then
+			showFailed "FAIL (F) $cname exists, please unload installed package."
+			exit 5
+		else
+			echo  "OK  (F)  $cname"
+		fi
+		;;
+	D)
+		#file
+		if [ -f "$cname" ]; then
+			showFailed "FAIL (D) $cname is a file, please check."
+		else
+			echo  "OK   (D) $cname"
+		fi
+
+		;;
+	I)
+		#info
+		showinfo  ">> check done."
+		;;
+
+	*)
+		#file
+		echo  "check        $XGROOT${value[1]}"
+
+	esac
+	
+}
 
 gpkg_mark_remove()
 {
@@ -1241,6 +1284,9 @@ gpkg_read()
 			;;
 		d)
 			gpkg_csvop_rm_dir
+			;;
+		c)
+			gpkg_csvop_check_file
 			;;
 		*)
 			gpkg_csvop_ls
@@ -1491,8 +1537,11 @@ gpkg_install_binary_package()
 	local xgbfile
 	local atom
 	local dbpath
+	local packname
+	local infofile
 
 	dbpath=${XGPATH_DB_RAW#/}
+	packname=$1
 
 	showinfo ">> parsing $1..."
 	#fine xgbfile in package.
@@ -1509,6 +1558,28 @@ gpkg_install_binary_package()
 
 	atom=${xgbfile##*/}
 	atom_parse "$atom"
+
+	showinfo ">> checking $T/$N-$V$R ..."
+
+	#check XG_DB_RAW
+	if [ "$XGPATH_DB_RAW" != "/var/xiange/db" ]; then
+		showFailed "XGPATH_DB_RAW changed to $XGPATH_DB_RAW."
+		exit 2
+	fi
+	#get .file from packet
+	mkdir -p /tmp/xiange/xib
+	err_check "[Error] make tmp /tmp/xiange/xib failed.\n"
+
+	infofile="var/xiange/db/$T/$N/$N-$V$R.file"
+	tar xf "$packname" -C /tmp/xiange/xib "$infofile" 
+	err_check "[Error] get file info from pack failed."
+
+	pushd /tmp/xiange/xib > /dev/null
+
+	#check all files
+	gpkg_readfile "$infofile" "c"
+	popd
+	rm -rf $infofile
 
 	showinfo ">> installing $T/$N-$V$R ..."
 
